"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['rt_notify.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'packages': 'keyring.backends',
    'plist': {
        'LSUIElement': True,
    },
    'iconfile': '57365.icns',
    'resources': '57365.png',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'beautifulsoup4>=4.3.2',
        'requests>=2.7.0',
        'pync>=1.6.1',
        'keyring>=5.3',
        'rumps>=0.2.1',
        'pyobjc>=3.0.4'
    ]
)
